dependencies:
  - python  
  - pip:
    - numpy
    - selfies
    - transformers
    - tqdm
    - torch
    - pandas
    - rdkit
    - datasets
    - wandb
    - attr
    - huggingface_hub
    - esm  
    - requests
    - lzma  

